# Evaluation Tasks
TASK_EXPECTED_ACTION = "expected_action"
TASK_LINGUISTIC_HABITS = "linguistic_habits"
TASK_PERSONA_CONSISTENCY = "persona_consistency"
TASK_TOXICITY_CONTROL = "toxicity_control"
TASK_ACTION_JUSTIFICATION = "action_justification"

TASK_NAMES = [
    TASK_EXPECTED_ACTION,
    TASK_LINGUISTIC_HABITS,
    TASK_PERSONA_CONSISTENCY,
    TASK_TOXICITY_CONTROL,
    TASK_ACTION_JUSTIFICATION,
]

SCORE_MIN = 1
SCORE_MAX = 5
SCORE_RANGE = (SCORE_MIN, SCORE_MAX)

DEFAULT_TEMPERATURE_GENERATOR = 0.9  # Creative generation
DEFAULT_TEMPERATURE_EVALUATOR = 0.0  # Deterministic evaluation

DEFAULT_QUESTIONS_PER_TASK = 10
DEFAULT_ENVIRONMENTS_PER_PERSONA = 10
